name = "SpectroscopicUnits"
uuid = "0254b9f8-588e-4adc-8079-5000bdf5a5ec"
authors = ["Olivier Merchiers <omerchiers@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Reexport = "0.2"
Unitful = "1.3"
PhysicalConstants = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
